#!/bin/bash

gcloud auth login
gcloud config set project cp-dev-fieldforce
gsutil cors set storage-cors-prod.json gs://cp-dev-fieldforce.appspot.com

gcloud storage buckets describe gs://cp-dev-fieldforce.appspot.com --format="default(cors_config)"