export const ERRORS: {[key:string]:string} = {
    "auth/wrong-password": "Wrong password",
    "auth/claims-too-large": "Claim too large",
    "auth/email-already-exists": "Email exist",
    "auth/id-token-expired": "Token expired",
    "auth/id-token-revoked": "Token revoked",
    "auth/insufficient-permission": "Insufficiant permission",
    "auth/internal-error": "Internal error",
    "auth/invalid-argument": "",
    "auth/invalid-claims": "Invalid claim",
    "auth/invalid-continue-uri": "Invalid uri",
    "auth/invalid-creation-time": "Invalide create time",
    "auth/invalid-credential": "Invalide credential",
    "auth/invalid-disabled-field": "Invalid field",
    "auth/invalid-display-name": "Invalid display name",
    "auth/invalid-dynamic-link-domain": "Invalid link",
    "auth/invalid-email": "Invalid email",
    "auth/invalid-email-verified": "Invalid email verification",
    "auth/invalid-hash-algorithm": "Invalid hash",
    "auth/invalid-hash-block-size": "Invalid hash",
    "auth/invalid-hash-derived-key-length": "Invalid hash",
    "auth/invalid-hash-key": "Invalid hash",
    "auth/invalid-hash-memory-cost": "Invalid hash",
    "auth/invalid-hash-parallelization": "Invalid hash",
    "auth/invalid-hash-rounds": "Invalid hash",
    "auth/invalid-hash-salt-separator": "Invalid salt separator",
    "auth/invalid-id-token": "Invalid token",
    "auth/invalid-last-sign-in-time": "Invalid sign in ",
    "auth/invalid-page-token": "Invalid page token",
    "auth/invalid-password": "Invalid password",
    "auth/invalid-password-hash": "Invalid password hash",
    "auth/invalid-password-salt": "Invalid password salt",
    "auth/invalid-phone-number": "Invalid phone number",
    "auth/invalid-photo-url": "Invalid photo url",
    "auth/invalid-provider-data": "Invalid provider data",
    "auth/invalid-provider-id": "Invalid auth provider",
    "auth/invalid-oauth-responsetype": "Invalid OAuth response",
    "auth/invalid-session-cookie-duration": "Ivalid session",
    "auth/invalid-uid": "Invalid UID",
    "auth/invalid-user-import": "Invalid user import",
    "auth/maximum-user-count-exceeded": "Max user count exceeded",
    "auth/missing-android-pkg-name": "Missing android package name",
    "auth/missing-continue-uri": "Missing uri",
    "auth/missing-hash-algorithm": "Missing hash algorithm",
    "auth/missing-ios-bundle-id": "Missing ios id",
    "auth/missing-uid": "Missing UID",
    "auth/missing-oauth-client-secret": "Invalid client",
    "auth/operation-not-allowed": "",
    "auth/phone-number-already-exists": "Phone number already exist",
    "auth/project-not-found": "Invalid project",
    "auth/reserved-claims": "Invalid claim",
    "auth/session-cookie-expired": "Invalid session",
    "auth/session-cookie-revoked": "Invalid session",
    "auth/uid-already-exists": "UID already exits",
    "auth/unauthorized-continue-uri": "Unauthorised",
    "auth/user-not-found": "User not found",
};

export function getAuthErrorMessage(code: string): string {
    return ERRORS[code] || code;
}
